DROP TABLE IF EXISTS opt_orders; --Код лектора--
DROP TABLE IF EXISTS opt_products;
DROP TABLE IF EXISTS opt_clients;

CREATE TABLE IF NOT EXISTS opt_clients (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS opt_products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_category VARCHAR(50) NOT NULL CHECK (
        product_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')
    ),
    description TEXT
);

CREATE TABLE IF NOT EXISTS opt_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    client_id UUID,
    product_id INTEGER,
    CONSTRAINT fk_opt_orders_client
        FOREIGN KEY (client_id) REFERENCES opt_clients(id),
    CONSTRAINT fk_opt_orders_product
        FOREIGN KEY (product_id) REFERENCES opt_products(product_id)
);

explain analyze --Неоптимізований варіант (ускладнений)--
select
	c.name, --Обираю колонки name, surname, product_id
	c.surname,
	p.product_id,
	count(*) as total_orders --Рахуємо кількість замовлень як total_orders--
from opt_orders o
join opt_clients c on o.client_id=c.id --Об'єдную таблиці clients i orders за їхніми id--
join opt_products p on o.product_id=p.product_id --Об'єднання таблиці products i orders теж за id--
where c.status='active' and o.order_date>'2023-10-10' --Фільтрування по статусу тільки активний і по даті--
group by p.product_id, c.name, c.surname, o.client_id, o.product_id --Виведення згрупованих колонок--
having count(*) =( --Ця частина, щоб це більше ускладнити ще раз починаємо цикл і так згрупованих даних--
	select count(*)
	from opt_orders o2
	where o2.client_id=o.client_id and o2.product_id=o.product_id and o2.order_date>'2023-10-10' --Ще раз повторюємо те саме--
);
--Створення індексів--
create index if not exists idx_order_date on opt_orders(order_date); --Індекс для пошуку по даті--

create index if not exists idx_client_id on opt_orders(client_id); --Індекс для швидкого об'єднання з клієнтами--

create index if not exists idx__status on opt_clients(status); --Індекс для пошуку по статусу клієнта--

explain analyze --Оптимізований варіант--
with active_clients as ( --Створення CTE--
	select id, name, surname
	from opt_clients
	where status='active' --Відразу обираємо тільки активних користувачів --
),
filtered_orders as ( --Ще одне CTE для фільтрації по даті--
	select client_id, product_id
	from opt_orders
	where order_date>'2023-10-10'
)
select
	c.name,
	c.surname,
	p.product_id,
	count(*) as total_orders --Так само як і в неоптимізованому рахуємо кількість замовлень--
from filtered_orders f --З фільтрованого CTE--
join active_clients c on f.client_id=c.id --Об'єднуємо два CTE за id--
join opt_products p on f.product_id=p.product_id --Об'єднуємо таблицю products i CTE по даті за id--
group by c.name, c.surname, p.product_id --Групуємо результат по name, surname, product_id--